

const base_url = "http://127.0.0.1:8000"
export const urls = {
  eliminar_usuarios: `${base_url}/api/eliminar-usuarios/`,
  listar_usuarios: `${base_url}/api/listar_usuarios/`,
  actualizar_pagos: `${base_url}/api/actualizar-pago/`,
  code_planing: `${base_url}/api/profe-plan/`,
  maestrias: `${base_url}/api/maestrias/`,
  pagos: `${base_url}/api/pagos/`,
  solicitudes: `${base_url}/api/solicitudes/`,
  login_admin: `${base_url}/api/admin-login/`,
  userInfo: `${base_url}/api/user-info/`,
  recuperar_contrasena: `${base_url}/api/recuperar-contrasena/`,
  cohortes: `${base_url}/api/cohortes/`,
  listado_profesores: `${base_url}/api/listado-profesores/`,
  listado_estudiantes: `${base_url}/api/listado_estudiantes/`,
  listado_materias: `${base_url}/api/listado-materias/`,
  asignar_profesor_materia: `${base_url}/api/asignar-profesor-materia/`,
  verificarCodigoCohort: `${base_url}/api/verificar-codigo-cohort/`,
  cohorte_generar_codigo: `${base_url}/api/cohorte-generar-codigo/`,
  datosbasicos: `${base_url}/api/datosbasicos/`,
  obtenerdatosbasicos: `${base_url}/api/obtenerdatos/`,
  almacenarestudiante: `${base_url}/api/almacenarestudiante/`,
  login_estudiante: `${base_url}/api/login_estudiante/`,
  login_profesor: `${base_url}/api/login_profesor/`,
  // estudiantes: `${base_url}/api/estudiantes/`,
  // notas: `${base_url}/api/notas/`,
  // profesores: `${base_url}/api/profesores/`,
  // register: `${base_url}/api/register/`,
}